version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
    cooldown:
      default-days: 14
    labels:
      - "devops"
      - "bot"
    groups:
      actions:
        patterns:
          - "*"
