# File generated with docstub

from collections.abc import Callable
from pathlib import Path

def accumulate_qualname(qualname: str, *, start_right: bool = ...) -> None: ...
def escape_qualname(name: str) -> str: ...
def _resolve_path_before_caching(func: Callable) -> Callable: ...
def module_name_from_path(path: Path) -> str: ...
def pyfile_checksum(path: Path) -> str: ...

class DocstubError(Exception):
    pass
