[tool.docstub]

# TODO not implemented and used yet
extend_grammar = """

"""

# Import information for type annotations, declared ahead of time.
#
# Each item maps an annotation name on the left side to a dictionary on the
# right side.
#
# Import information can be declared with the following fields:
#     from : Indicate that the DocType can be imported from this path.
#     import : Import this object, defaults to the DocType.
#     as : Use this alias for the imported object
#     is_builtin : Indicate that this DocType doesn't need to be imported,
#         defaults to "false"
[tool.docstub.known_imports]
Path = { from = "pathlib" }
Callable = { from = "typing" }
np = { import = "numpy", as = "np" }
NDArray = { from = "numpy.typing" }
ArrayLike = { from = "numpy.typing" }

# Specify human-friendly aliases that can be used instead of Python-parsable
# annotations.
# TODO rename to qualname_alias or something
[tool.docstub.replace_doctypes]
iterable = "Iterable"
callable = "Callable"
function = "Callable"
func = "Callable"
sequence = "Sequence"
mapping = "Mapping"

numpy = "np"
scalar = "np.ScalarType"
integer = "np.integer"
signedinteger = "np.signedinteger"
byte ="np.byte"
short = "np.short"
intc = "np.intc"
int_ = "np.int_"
longlong = "np.longlong"
int8 = "np.int8"
int16 = "np.int16"
int32 = "np.int32"
int64 = "np.int64"
intp = "np.intp"
unsignedinteger = "np.unsignedinteger"
ushort = "np.ushort"
uintc = "np.uintc"
uint = "np.uint"
ulonglong ="np.ulonglong"
uint8 = "np.uint8"
uint16 = "np.uint16"
uint32 = "np.uint32"
uint64 = "np.uint64"
uintp = "np.uintp"
floating = "np.floating"
#half = "np.half"
#single = "np.single"
double = "np.double"
longdouble = "np.longdouble"
float16 = "np.float16"
float32 = "np.float32"
float64 = "np.float64"
float96 = "np.float96"
float128 = "np.float128"
complexfloating = "np.complexfloating"
csingle = "np.csingle"
cdouble = "np.cdouble"
clongdouble = "np.clongdouble"
complex64 = "np.complex64"
complex128 = "np.complex128"
complex192 = "np.complex192"
complex256 = "np.complex256"
bool_ = "np.bool_"
datetime64 = "np.datetime64"
timedelta64 = "np.timedelta64"
object_ = "np.object_"
#flexible = "np.flexible"
#character = "np.character"
bytes_ = "np.bytes_"
#str_ = "np.str_"
#void = "np.void"
ndarray = "NDArray"
array = "NDArray"
array-like = "ArrayLike"
array_like = "ArrayLike"
