[tool.docstub]

# Types and their external modules to use in docstrings.
[tool.docstub.types]
NDArray = "numpy.typing"
ArrayLike = "numpy.typing"


# Prefixes for external modules to match types in docstrings.
[tool.docstub.type_prefixes]
np = "numpy"
numpy = "numpy"


# Nicknames for types that can be used in docstrings to describe valid Python
# types or annotations.
[tool.docstub.type_nicknames]
scalar = "np.ScalarType"
integer = "np.integer"
signedinteger = "np.signedinteger"
#byte ="np.byte"
#short = "np.short"
intc = "np.intc"
#int_ = "np.int_"
longlong = "np.longlong"
int8 = "np.int8"
int16 = "np.int16"
int32 = "np.int32"
int64 = "np.int64"
intp = "np.intp"
unsignedinteger = "np.unsignedinteger"
ushort = "np.ushort"
uintc = "np.uintc"
uint = "np.uint"
ulonglong ="np.ulonglong"
uint8 = "np.uint8"
uint16 = "np.uint16"
uint32 = "np.uint32"
uint64 = "np.uint64"
uintp = "np.uintp"
floating = "np.floating"
#half = "np.half"
#single = "np.single"
double = "np.double"
longdouble = "np.longdouble"
float16 = "np.float16"
float32 = "np.float32"
float64 = "np.float64"
float96 = "np.float96"
float128 = "np.float128"
complexfloating = "np.complexfloating"
csingle = "np.csingle"
cdouble = "np.cdouble"
clongdouble = "np.clongdouble"
complex64 = "np.complex64"
complex128 = "np.complex128"
complex192 = "np.complex192"
complex256 = "np.complex256"
#bool_ = "np.bool_"
datetime64 = "np.datetime64"
timedelta64 = "np.timedelta64"
#object_ = "np.object_"
#flexible = "np.flexible"
#character = "np.character"
#bytes_ = "np.bytes_"
#str_ = "np.str_"
#void = "np.void"
ndarray = "NDArray"
array = "NDArray"
array-like = "ArrayLike"
array_like = "ArrayLike"
