[tool.docstub]

# Prefixes for external modules to match types in docstrings.
# Docstub can't yet automatically discover where to import types from other
# packages from. Instead, you can provide this information explicitly.
# Any type in a docstring whose prefix matches the name given on the left side,
# will be associated with the given "module" on the right side.
#
# Examples:
# np = "numpy"
#     Will match `np.uint8` and `np.typing.NDarray` and use "import numpy as np".
#
# plt = "matplotlib.pyplot
#     Will match `plt.Figure` use `import matplotlib.pyplot as plt`.
[tool.docstub.type_prefixes]
configparser = "configparser"
