[tool.docstub]

# TODO not implemented and used yet
extend_grammar = """

"""

# Import information for type annotations, declared ahead of time.
#
# Each item maps an annotation name on the left side to a dictionary on the
# right side.
#
# Import information can be declared with the following fields:
#     from : Indicate that the DocType can be imported from this path.
#     import : Import this object, defaults to the DocType.
#     as : Use this alias for the imported object
#     is_builtin : Indicate that this DocType doesn't need to be imported,
#         defaults to "false"
[tool.docstub.known_imports]
configparser = {import = "configparser"}
