# File generated with docstub

import logging
import re
import sys
from collections.abc import Generator, Sequence
from functools import lru_cache
from pathlib import Path

if sys.version_info >= (3, 13):
    from glob import translate as glob_translate
else:
    from ._vendored.stdlib import glob_translate

logger: logging.Logger

STUB_HEADER_COMMENT: str

def is_docstub_generated(stub_path: Path) -> bool: ...
def is_python_or_stub_file(path: Path) -> bool: ...
def is_python_package_dir(path: Path) -> bool: ...
def find_package_root(path: Path) -> Path: ...
def glob_patterns_to_regex(
    patterns: tuple[str, ...], relative_to: Path | None = ...
) -> re.Pattern | None: ...
def _walk_source_package(
    path: Path, *, ignore_regex: re.Pattern
) -> Generator[Path]: ...
def walk_source_package(
    path: Path, *, ignore: Sequence[str] = ...
) -> Generator[Path]: ...
def walk_source_and_targets(
    root_path: Path, target_dir: Path, *, ignore: Sequence[str] = ...
) -> Generator[tuple[Path, Path]]: ...
