# File generated with docstub

import itertools
import re
from collections.abc import Callable, Hashable, Mapping, Sequence
from functools import lru_cache, wraps
from pathlib import Path
from zlib import crc32

def accumulate_qualname(qualname: str, *, start_right: bool = ...) -> None: ...
def escape_qualname(name: str) -> str: ...
def _resolve_path_before_caching(func: Callable) -> Callable: ...
def module_name_from_path(path: Path) -> str: ...
def pyfile_checksum(path: Path) -> str: ...
def update_with_add_values(
    *mappings: Mapping[Hashable, int | Sequence], out: dict | None = ...
) -> dict: ...

class DocstubError(Exception):
    pass
